# Generated by Django 5.2.17 on 2026-10-01 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("matters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "bank_statement_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "cashbook_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("ledger_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "outstanding_deposits",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "outstanding_payments",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrustTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt (money in)"),
                            ("payment", "Payment (money out)"),
                            ("fee_transfer", "Transfer to business (fees)"),
                            ("transfer_in", "Transfer in from matter"),
                            ("transfer_out", "Transfer out to matter"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Always positive.", max_digits=14
                    ),
                ),
                (
                    "signed_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="received from / paid to",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("reconciled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_transfers",
                        to="billing.invoice",
                    ),
                ),
                (
                    "linked",
                    models.OneToOneField(
                        blank=True,
                        help_text="Other side of a matter-to-matter transfer.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_from",
                        to="trust.trusttransaction",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_transactions",
                        to="matters.matter",
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="trust.trusttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
    ]
