# Generated by Django 5.2.17 on 2026-10-01 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("matters", "0001_initial"),
        ("trust", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="trust_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="trust.trusttransaction",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_entries",
                to="matters.matter",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="fee earner",
            ),
        ),
    ]
