# Generated by Django 5.2.17 on 2026-10-01 13:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My Law Firm", max_length=200)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="VAT / tax number"
                    ),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=5)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="VAT rate (%)",
                    ),
                ),
                (
                    "default_hourly_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("150.00"), max_digits=10
                    ),
                ),
                ("matter_prefix", models.CharField(default="MAT", max_length=10)),
                ("client_prefix", models.CharField(default="CL", max_length=10)),
                ("invoice_prefix", models.CharField(default="INV", max_length=10)),
                ("invoice_due_days", models.PositiveIntegerField(default=30)),
                (
                    "business_bank_details",
                    models.TextField(blank=True, help_text="Printed on fee notes."),
                ),
                ("trust_bank_name", models.CharField(blank=True, max_length=100)),
                ("trust_account_number", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "firm settings",
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=20)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("partner", "Partner / Director"),
                            ("associate", "Associate"),
                            ("candidate", "Candidate attorney / Clerk"),
                            ("secretary", "Secretary"),
                            ("bookkeeper", "Bookkeeper"),
                        ],
                        default="associate",
                        max_length=20,
                    ),
                ),
                ("initials", models.CharField(blank=True, max_length=5)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
