# Generated by Django 5.2.17 on 2026-10-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmsettings",
            name="require_two_factor",
            field=models.BooleanField(
                default=False,
                help_text="Everyone must set up an authenticator app on their phone before using the system.",
                verbose_name="Require two-factor sign-in for all users",
            ),
        ),
    ]
