# Generated by Django 5.2.17 on 2026-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_firmsettings_require_two_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmsettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Printed on fee notes and statements (PNG or JPG).",
                upload_to="firm/",
            ),
        ),
    ]
