# Generated by Django 5.2.17 on 2026-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company / Organisation"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="ID / registration number",
                    ),
                ),
                ("vat_number", models.CharField(blank=True, max_length=50)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("physical_address", models.TextField(blank=True)),
                ("postal_address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
