# Generated by Django 5.2.17 on 2026-10-01 13:27

import django.db.models.deletion
import matters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "matter_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Any"),
                            ("litigation", "Litigation"),
                            ("conveyancing", "Conveyancing / Property"),
                            ("estates", "Deceased estates / Wills"),
                            ("commercial", "Commercial / Corporate"),
                            ("family", "Family / Divorce"),
                            ("labour", "Labour"),
                            ("criminal", "Criminal"),
                            ("collections", "Collections / Debt recovery"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Merge fields: {{ firm.name }}, {{ client.name }}, {{ client.physical_address }}, {{ matter.file_number }}, {{ matter.description }}, {{ matter.opposing_party }}, {{ matter.case_number }}, {{ author }}, {{ today }}"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "matter_type",
                    models.CharField(
                        choices=[
                            ("litigation", "Litigation"),
                            ("conveyancing", "Conveyancing / Property"),
                            ("estates", "Deceased estates / Wills"),
                            ("commercial", "Commercial / Corporate"),
                            ("family", "Family / Divorce"),
                            ("labour", "Labour"),
                            ("criminal", "Criminal"),
                            ("collections", "Collections / Debt recovery"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("on_hold", "On hold"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("date_opened", models.DateField()),
                ("date_closed", models.DateField(blank=True, null=True)),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly / time based"),
                            ("fixed", "Fixed fee"),
                            ("contingency", "Contingency"),
                        ],
                        default="hourly",
                        max_length=20,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides the fee earner's rate.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fixed_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("opposing_party", models.CharField(blank=True, max_length=200)),
                ("opposing_attorney", models.CharField(blank=True, max_length=200)),
                ("court", models.CharField(blank=True, max_length=200)),
                ("case_number", models.CharField(blank=True, max_length=100)),
                (
                    "prescription_date",
                    models.DateField(
                        blank=True, help_text="Date the claim prescribes.", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matters",
                        to="clients.client",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsible attorney",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_opened", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FileNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_notes",
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to=matters.models.document_path)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
