# Generated by Django 5.2.17 on 2026-10-01 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "matter_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Any"),
                            ("litigation", "Litigation"),
                            ("conveyancing", "Conveyancing / Property"),
                            ("estates", "Deceased estates / Wills"),
                            ("commercial", "Commercial / Corporate"),
                            ("family", "Family / Divorce"),
                            ("labour", "Labour"),
                            ("criminal", "Criminal"),
                            ("collections", "Collections / Debt recovery"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=True,
                        help_text="Add these steps automatically when a matter of this type is opened.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MatterTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("workflow", models.CharField(blank=True, max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=300)),
                (
                    "due_after_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days after the matter is opened that this step is due.",
                        null=True,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="matters.workflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
